spring:
  application:
    name: e-learning-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/elearning
    username: postgres
    password: mfchongm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
